channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gunicorn
  - gevent
  - xgboost
  - mlflow
  - scikit-learn
  - numpy
  - pandas
  - click
  - pip:
    - cloudpickle==1.3.0
name: mushroom-model
